[2023-04-10T17:19:38.428+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 10X_sequence.archive_run_dir Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T17:19:38.460+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 10X_sequence.archive_run_dir Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T17:19:38.461+0400] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T17:19:38.461+0400] {taskinstance.py:1289} INFO - Starting attempt 3 of 5
[2023-04-10T17:19:38.462+0400] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T17:19:38.509+0400] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): archive_run_dir> on 2023-04-10 08:47:10.123376+00:00
[2023-04-10T17:19:38.522+0400] {standard_task_runner.py:55} INFO - Started process 12113 to run task
[2023-04-10T17:19:38.533+0400] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '10X_sequence', 'archive_run_dir', 'Airflow_test_cell_ranger_10_04_2023 12_47_08', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/10X_sequence_dag.py', '--cfg-path', '/tmp/tmpkfdftpa6']
[2023-04-10T17:19:38.534+0400] {standard_task_runner.py:83} INFO - Job 32: Subtask archive_run_dir
[2023-04-10T17:19:38.748+0400] {task_command.py:389} INFO - Running <TaskInstance: 10X_sequence.archive_run_dir Airflow_test_cell_ranger_10_04_2023 12_47_08 [running]> on host e286faa700a5
[2023-04-10T17:19:38.983+0400] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=10X_sequence
AIRFLOW_CTX_TASK_ID=archive_run_dir
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T08:47:10.123376+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=Airflow_test_cell_ranger_10_04_2023 12_47_08
[2023-04-10T17:19:39.005+0400] {base.py:73} INFO - Using connection ID '***_docker_ssh' for task execution.
[2023-04-10T17:19:39.007+0400] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-04-10T17:19:39.019+0400] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2023-04-10T17:19:39.268+0400] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-04-10T17:19:39.269+0400] {ssh_helpers.py:43} INFO - Executing command: rsync -av  /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 /archive/gencore/novaseq/
[2023-04-10T17:19:39.989+0400] {ssh_helpers.py:75} INFO - sending incremental file list
[2023-04-10T17:19:41.723+0400] {ssh_helpers.py:75} INFO - 
[2023-04-10T17:19:41.724+0400] {ssh_helpers.py:75} INFO - sent 133,091 bytes  received 916 bytes  53,602.80 bytes/sec
total size is 261,363,575,855  speedup is 1,950,372.56
[2023-04-10T17:19:41.737+0400] {ssh_helpers.py:94} INFO - Command exited with exitcode 0
[2023-04-10T17:19:41.738+0400] {python.py:177} INFO - Done. Returned value was: None
[2023-04-10T17:19:41.774+0400] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=10X_sequence, task_id=archive_run_dir, execution_date=20230410T084710, start_date=20230410T131938, end_date=20230410T131941
[2023-04-10T17:19:41.830+0400] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-10T17:19:41.884+0400] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
