[2023-04-10T13:01:04.815+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T13:01:04.849+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T13:01:04.850+0400] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T13:01:04.851+0400] {taskinstance.py:1289} INFO - Starting attempt 2 of 3
[2023-04-10T13:01:04.851+0400] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T13:01:04.887+0400] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): demultiplex> on 2023-04-10 08:47:10.123376+00:00
[2023-04-10T13:01:04.894+0400] {standard_task_runner.py:55} INFO - Started process 751 to run task
[2023-04-10T13:01:04.897+0400] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '10X_sequence', 'demultiplex', 'Airflow_test_cell_ranger_10_04_2023 12_47_08', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/10X_sequence_dag.py', '--cfg-path', '/tmp/tmpt6ttowen']
[2023-04-10T13:01:04.898+0400] {standard_task_runner.py:83} INFO - Job 22: Subtask demultiplex
[2023-04-10T13:01:04.995+0400] {task_command.py:389} INFO - Running <TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [running]> on host e286faa700a5
[2023-04-10T13:01:05.151+0400] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=10X_sequence
AIRFLOW_CTX_TASK_ID=demultiplex
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T08:47:10.123376+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=Airflow_test_cell_ranger_10_04_2023 12_47_08
[2023-04-10T13:01:05.171+0400] {base.py:73} INFO - Using connection ID '***_docker_ssh' for task execution.
[2023-04-10T13:01:05.173+0400] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-04-10T13:01:05.185+0400] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2023-04-10T13:01:05.350+0400] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-04-10T13:01:06.060+0400] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2023-04-10T13:01:06.144+0400] {logging_mixin.py:137} INFO - #!/bin/bash
#SBATCH --output=NCS-400-demultiplex_%A.out
#SBATCH --error=NCS-400-demultiplex_%A.err
#SBATCH -J NCS-400-demultiplex
#SBATCH --nodes=1
#SBATCH -A gencore
#SBATCH --ntasks=1
#SBATCH --partition=gencore
#SBATCH --cpus-per-task=28
#SBATCH --time=1000:00:00
#SBATCH --mem 420000


cd /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 && \
        cellranger mkfastq -R /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 \
        --csv=10xsimple.csv --id=NCS-400 \
        --output-dir NCS-400 --jobmode=local \
        --localcores=28 --localmem=400  \
[2023-04-10T13:01:06.155+0400] {ssh_helpers.py:134} INFO - ====================================================
[2023-04-10T13:01:06.156+0400] {ssh_helpers.py:135} INFO - Executing command: 
cd /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 && chmod 777 *sh && sh /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2/demultiplex.sh
[2023-04-10T13:01:06.156+0400] {ssh_helpers.py:136} INFO - ====================================================
[2023-04-10T13:09:58.357+0400] {local_task_job.py:277} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-04-10T13:09:58.364+0400] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 751. PIDs of all processes in the group: [751]
[2023-04-10T13:09:58.365+0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 751
[2023-04-10T13:09:58.365+0400] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-10T13:09:58.366+0400] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/ssh_helpers.py", line 163, in execute_ssh_command_return_stdout_stderr
    readq, _, _ = select([channel], [], [], timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1490, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demultiplex_ten.py", line 134, in run_demultiplex_task
    output = submit_demultiplex_job_to_slurm(ssh, sftp, kwargs)
  File "/opt/airflow/dags/demultiplex_ten.py", line 71, in submit_demultiplex_job_to_slurm
    slurm_command, logger)
  File "/opt/airflow/dags/ssh_helpers.py", line 202, in execute_ssh_command_return_stdout_stderr
    raise Exception("SSH operator error: {0}".format(str(e)))
Exception: SSH operator error: Task received SIGTERM signal
[2023-04-10T13:09:58.395+0400] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=10X_sequence, task_id=demultiplex, execution_date=20230410T084710, start_date=20230410T090104, end_date=20230410T090958
[2023-04-10T13:09:58.443+0400] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task demultiplex (SSH operator error: Task received SIGTERM signal; 751)
[2023-04-10T13:09:58.498+0400] {process_utils.py:79} INFO - Process psutil.Process(pid=751, status='terminated', exitcode=1, started='13:01:04') (751) terminated with exit code 1
