[2023-04-10T13:11:10.971+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T13:11:10.985+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T13:11:10.985+0400] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T13:11:10.985+0400] {taskinstance.py:1289} INFO - Starting attempt 3 of 4
[2023-04-10T13:11:10.985+0400] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T13:11:11.004+0400] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): demultiplex> on 2023-04-10 08:47:10.123376+00:00
[2023-04-10T13:11:11.013+0400] {standard_task_runner.py:55} INFO - Started process 1211 to run task
[2023-04-10T13:11:11.022+0400] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '10X_sequence', 'demultiplex', 'Airflow_test_cell_ranger_10_04_2023 12_47_08', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/10X_sequence_dag.py', '--cfg-path', '/tmp/tmpmmv1aptd']
[2023-04-10T13:11:11.023+0400] {standard_task_runner.py:83} INFO - Job 24: Subtask demultiplex
[2023-04-10T13:11:11.194+0400] {task_command.py:389} INFO - Running <TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [running]> on host e286faa700a5
[2023-04-10T13:11:11.435+0400] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=10X_sequence
AIRFLOW_CTX_TASK_ID=demultiplex
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T08:47:10.123376+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=Airflow_test_cell_ranger_10_04_2023 12_47_08
[2023-04-10T13:11:11.460+0400] {base.py:73} INFO - Using connection ID '***_docker_ssh' for task execution.
[2023-04-10T13:11:11.462+0400] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-04-10T13:11:11.474+0400] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2023-04-10T13:11:11.737+0400] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-04-10T13:11:12.498+0400] {sftp.py:169} INFO - [chan 0] Opened sftp connection (server version 3)
[2023-04-10T13:11:12.587+0400] {logging_mixin.py:137} INFO - #!/bin/bash
#SBATCH --output=NCS-400-demultiplex_%A.out
#SBATCH --error=NCS-400-demultiplex_%A.err
#SBATCH -J NCS-400-demultiplex
#SBATCH --nodes=1
#SBATCH -A gencore
#SBATCH --ntasks=1
#SBATCH --partition=gencore
#SBATCH --cpus-per-task=28
#SBATCH --time=1000:00:00
#SBATCH --mem 420000


cd /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 && \
        cellranger mkfastq -R /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 \
        --csv=10xsimple.csv --id=NCS-400 \
        --output-dir NCS-400 --jobmode=local \
        --localcores=28 --localmem=400  \
[2023-04-10T13:11:12.600+0400] {ssh_helpers.py:134} INFO - ====================================================
[2023-04-10T13:11:12.601+0400] {ssh_helpers.py:135} INFO - Executing command: 
cd /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2 && chmod 777 *sh && sbatch /scratch/gencore/novaseq/221130_A00534_0114_BHHYF3DRX2/demultiplex.sh
[2023-04-10T13:11:12.601+0400] {ssh_helpers.py:136} INFO - ====================================================
[2023-04-10T13:11:13.354+0400] {ssh_helpers.py:184} INFO - Command Output
[2023-04-10T13:11:13.355+0400] {ssh_helpers.py:185} INFO - ====================================================
[2023-04-10T13:11:13.355+0400] {ssh_helpers.py:186} INFO - Submitted batch job 1428852
[2023-04-10T13:11:13.355+0400] {ssh_helpers.py:187} INFO - ====================================================
[2023-04-10T13:11:13.356+0400] {ssh_helpers.py:195} INFO - Command exited with exitcode 0
[2023-04-10T13:12:13.409+0400] {slurm_helpers.py:53} INFO - Polling slurm job 1428852
[2023-04-10T13:12:13.410+0400] {ssh_helpers.py:134} INFO - ====================================================
[2023-04-10T13:12:13.410+0400] {ssh_helpers.py:135} INFO - Executing command: sacct -a -j 1428852
[2023-04-10T13:12:13.410+0400] {ssh_helpers.py:136} INFO - ====================================================
[2023-04-10T13:12:14.136+0400] {ssh_helpers.py:184} INFO - Command Output
[2023-04-10T13:12:14.136+0400] {ssh_helpers.py:185} INFO - ====================================================
[2023-04-10T13:12:14.137+0400] {ssh_helpers.py:186} INFO -        JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
1428852      NCS-400-d+    gencore    gencore         28     FAILED      1:0 
1428852.bat+      batch               gencore         28     FAILED      1:0 
1428852.ext+     extern               gencore         28  COMPLETED      0:0 
[2023-04-10T13:12:14.137+0400] {ssh_helpers.py:187} INFO - ====================================================
[2023-04-10T13:12:14.137+0400] {ssh_helpers.py:195} INFO - Command exited with exitcode 0
[2023-04-10T13:12:14.138+0400] {slurm_helpers.py:63} INFO - Current job status: COMPLETED
[2023-04-10T13:13:23.161+0400] {local_task_job.py:277} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-04-10T13:13:23.167+0400] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1211. PIDs of all processes in the group: [1211]
[2023-04-10T13:13:23.168+0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1211
[2023-04-10T13:13:23.169+0400] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-10T13:13:23.196+0400] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demultiplex_ten.py", line 136, in run_demultiplex_task
    poll_slurm_job(ssh, slurm_job_id)
  File "/opt/airflow/dags/slurm_helpers.py", line 71, in poll_slurm_job
    time.sleep(300)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1490, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-04-10T13:13:23.207+0400] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=10X_sequence, task_id=demultiplex, execution_date=20230410T084710, start_date=20230410T091110, end_date=20230410T091323
[2023-04-10T13:13:23.240+0400] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task demultiplex (Task received SIGTERM signal; 1211)
[2023-04-10T13:13:23.261+0400] {process_utils.py:79} INFO - Process psutil.Process(pid=1211, status='terminated', exitcode=1, started='13:11:10') (1211) terminated with exit code 1
